plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.jetbrains/annotations
    implementation 'org.jetbrains:annotations:26.0.2'
    // https://mvnrepository.com/artifact/uk.ac.abdn/SimpleNLG
    implementation 'uk.ac.abdn:SimpleNLG:4.4.8'
    // https://mvnrepository.com/artifact/gov.nih.nlm.nls.lexaccess/lexaccess-dist
    implementation 'gov.nih.nlm.nls.lexaccess:lexaccess-dist:2013'

    testImplementation platform('org.junit:junit-bom:5.13.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}